#-------------------------------
# General Site Settings
baseurl: "/ibucgunyeni" # the subpath of your site, e.g. /blog
url: "ibucgun.github.io/ibucgunyeni/" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num"


#-------------------------------
# Collections
collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  works:
    output: true
    permalink: /calisma-alani/:slug
  egitim:
    output: true
    permalink: /egitim/:slug

# Pages Path
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "egitim"
    values:
      layout: "egitim"

sass:
  sass_dir: _sass
  style: compressed